Ext.define('Gongzhu.model.Product', {
    extend: 'Ext.data.Model',
    fields: [
    'add_time',
    'area_id',
    'attribute',
    'brand_id',
    'capacity',
    'cat_id',
    'chname',
    'desc',
    'enname',  
    'icon',
    'image_url',
    'importUrl',
    'importurl',
    'is_delete',
    'letter',
    'memo',
    'parent_id',
    'pindex',
    'price',
    'product_id',
    'product_name',
    'published',
    'sort',
    'stars',
    'tag_id',
    'threads',
    'time',
    'update_time',
    'useds',
    'wantuses'
    ],
   
});